sudo: false
language: node_js
matrix:
  include:
  - node_js: 6.3 # Current
    env: BUILD_DOCS=true REPORT_COVERAGE=true
  - node_js: 4.4 # LTS
    env: NPM_DEPLOY=true
  - node_js: 4.0 # Minimum supported
script:
- npm test -- -- --timeout 10000
after_success:
- '[[ "$REPORT_COVERAGE" != true ]] || cat coverage/lcov.info | ./node_modules/.bin/codecov'
- '[[ "$REPORT_COVERAGE" != true ]] || cat coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter'
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: amercier/karma-scss-preprocessor # Prevents publishing on PRs
    condition: $NPM_DEPLOY = true # Prevents publishing on each matrix build
cache:
  directories:
  - $HOME/.nvm
